import pandas as pd

class DataProfiler:
    """Automates statistical baselining and data quality checks."""
    
    # Initialize the class by passing in the DataFrame generated by our FileConnector
    def __init__(self, dataframe: pd.DataFrame):
        self.df = dataframe

    # The main method that triggers the math operations
    def generate_summary(self) -> pd.DataFrame:
        """Returns a high-density DataFrame summarizing dataset health."""
        
        # We start by building a dictionary of the most critical structural metrics
        # We process the entire DataFrame column by column
        summary_data = {
            # Extracts the datatype (int, float, object/string) for each column
            'Data_Type': self.df.dtypes,
            
            # Calculates the total number of rows in the DataFrame
            'Total_Rows': len(self.df),
            
            # Counts the exact number of missing (Null/NaN) values per column
            'Missing_Count': self.df.isnull().sum(),
            
            # Calculates the percentage of missing data, rounded to 2 decimal points
            'Missing_Pct': (self.df.isnull().sum() / len(self.df) * 100).round(2),
            
            # Counts how many unique, distinct values exist in each column (Cardinality)
            'Unique_Values': self.df.nunique()
        }
        
        # Convert our dictionary into a structured Pandas DataFrame
        summary = pd.DataFrame(summary_data)

        # Statistical math (Mean, Min, Max) will crash if applied to text columns.
        # This line isolates ONLY the columns that contain numeric data.
        numeric_cols = self.df.select_dtypes(include=['number']).columns
        
        # Apply statistical functions strictly to the isolated numeric columns
        # We append these new columns to our summary DataFrame
        summary['Min'] = self.df[numeric_cols].min()
        summary['Max'] = self.df[numeric_cols].max()
        summary['Mean'] = self.df[numeric_cols].mean().round(2)
        summary['Std_Dev'] = self.df[numeric_cols].std().round(2)

        return summary